// <auto-generated />
namespace MvcOnlineTicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig46 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig46));
        
        string IMigrationMetadata.Id
        {
            get { return "202512221157152_mig46"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
